import { Router } from "express";
import auth from "./auth.routes.js";
import stores from "./stores.routes.js";
import shops from "./shops.routes.js";
import reservation from "./reservation.routes.js";
import shopReservations from "./shopReservations.routes.js";
import shopSlots from "./shopSlots.routes.js";
import shopCategories from "./shopCategories.routes.js";
import shopProducts from "./shopProducts.routes.js";
import shopInventory from "./shopInventory.routes.js";
import shopOrders from "./shopOrders.routes.js";
import shopKds from "./shopKds.routes.js";
import shopCoupons from "./shopCoupons.routes.js";
import shopReviews from "./shopReviews.routes.js";
import shopRegisters from "./shopRegisters.routes.js";
import shopAnalytics from "./shopAnalytics.routes.js";
import shopFinance from "./shopFinance.routes.js";
import shopJobs from "./shopJobs.routes.js";
import shopLine from "./shopLine.routes.js";
import orders from "./orders.routes.js";
import kds from "./kds.routes.js";
import tables from "./tables.routes.js";
import business from "./business.routes.js";
import staff from "./staff.routes.js";
import storeconfig from "./storeconfig.routes.js";
import users from "./users.routes.js";

const r = Router();
r.use("/auth", auth);
r.use("/users", users);
r.use("/stores", stores);
r.use("/shops", shops);
r.use("/reservations", reservation);
r.use("/shops/:shopId/reservations", shopReservations);
r.use("/shops/:shopId/slots", shopSlots);
r.use("/shops/:shopId/categories", shopCategories);
r.use("/shops/:shopId/products", shopProducts);
r.use("/shops/:shopId/inventory", shopInventory);
r.use("/shops/:shopId/orders", shopOrders);
r.use("/shops/:shopId/kds", shopKds);
r.use("/shops/:shopId/coupons", shopCoupons);
r.use("/shops/:shopId/reviews", shopReviews);
r.use("/shops/:shopId/registers", shopRegisters);
r.use("/shops/:shopId/analytics", shopAnalytics);
r.use("/shops/:shopId/finance", shopFinance);
r.use("/shops/:shopId/jobs", shopJobs);
r.use("/shops/:shopId/line/broadcasts", shopLine);
r.use("/orders", orders);
r.use("/kds", kds);
r.use("/tables", tables);
r.use("/business", business);
r.use("/staffs", staff);
r.use("/storeconfig", storeconfig);

export default r;
