import { Router } from "express";
import auth from "./auth.routes.js";
import stores from "./stores.routes.js";
import shops from "./shops.routes.js";
import menu from "./menu.routes.js";
import inventory from "./inventory.routes.js";
import reservation from "./reservation.routes.js";
import shopReservations from "./shopReservations.routes.js";
import shopSlots from "./shopSlots.routes.js";
import shopCategories from "./shopCategories.routes.js";
import shopProducts from "./shopProducts.routes.js";
import shopInventory from "./shopInventory.routes.js";
import shopOrders from "./shopOrders.routes.js";
import shopKds from "./shopKds.routes.js";
import orders from "./orders.routes.js";
import kds from "./kds.routes.js";
import tables from "./tables.routes.js";
import business from "./business.routes.js";
import staff from "./staff.routes.js";
import storeconfig from "./storeconfig.routes.js";

const r = Router();
r.use("/auth", auth);
r.use("/stores", stores);
r.use("/shops", shops);
r.use("/menu", menu);
r.use("/inventory", inventory);
r.use("/reservations", reservation);
r.use("/shops/:shopId/reservations", shopReservations);
r.use("/shops/:shopId/slots", shopSlots);
r.use("/shops/:shopId/categories", shopCategories);
r.use("/shops/:shopId/products", shopProducts);
r.use("/shops/:shopId/inventory", shopInventory);
r.use("/shops/:shopId/orders", shopOrders);
r.use("/shops/:shopId/kds", shopKds);
r.use("/orders", orders);
r.use("/kds", kds);
r.use("/tables", tables);
r.use("/business", business);
r.use("/staffs", staff);
r.use("/storeconfig", storeconfig);

export default r;
